kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:12-alpine
    commands:
      - npm install
      - npm install -g @angular/cli
      - ng build --prod
  - name: docker
    image: plugins/docker
    settings:
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repo: $DOCKER_REPOSITORY
      tags: latest
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DOCKER_REPOSITORY:
        from_secret: DOCKER_REPOSITORY
    depends_on: [build]
  - name: deploy
    image: caprover/cli-caprover:latest
    commands:
      - npx caprover deploy -h $CAPROVER_DOMAIN -p $CAPROVER_PASSWORD -i $DOCKER_REPOSITORY:latest -a $CAPROVER_APPNAME
    environment:
      CAPROVER_DOMAIN:
        from_secret: CAPROVER_DOMAIN
      CAPROVER_APPNAME:
        from_secret: CAPROVER_APPNAME
      CAPROVER_PASSWORD:
        from_secret: CAPROVER_PASSWORD
      DOCKER_REPOSITORY:
        from_secret: DOCKER_REPOSITORY
    depends_on: [docker]
